[template]
cargo_generate_version = ">=0.23.0"

[hooks]
pre = [
    "script-task-license.rhai"
]
post = ["script-post.rhai"]

[placeholders]
description = { type = "string", prompt = "Description for this service?" }